# Generated by Django 2.1 on 2019-09-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre:')),
                ('descripcion', models.TextField(max_length=45)),
                ('empresa', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField(null=True)),
            ],
        ),
    ]
