# Generated by Django 2.1 on 2019-09-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
